"""Distribute research evidence and the repo catalog into the domain folders.

Run from the toolkit root after a Deep Recon Refresh:  python _research/distribute.py
- Writes <folder>/docs/evidence.md  (sections of both research.md reports + their sources)
- Writes <folder>/docs/repos.md     (repo tables from _research/.../repo-tables.md)
Source files are never modified; outputs are regenerated each run.
"""
import os
import re

ROOT = os.getcwd()
T = "_research/technical-hackathon-toolkit-2026-09-21/research.md"
G = "_research/technical-hackathon-github-repos-2026-09-21/research.md"
TABLES = "_research/technical-hackathon-github-repos-2026-09-21/repo-tables.md"

# folder -> (title, [(report, section-number, prefix)])
EVIDENCE = {
    "01-hackathon-playbook": ("Hackathon strategy, pitching & free credits", [(T, 1, "T"), (T, 9, "T")]),
    "02-frontend": ("Frontend & mobile", [(T, 2, "T"), (T, 8, "T"), (G, 1, "G")]),
    "03-backend": ("Backend, Web3, plumbing & deployment", [(T, 3, "T"), (T, 7, "T"), (T, 9, "T"), (T, 10, "T"), (G, 2, "G")]),
    "04-ai-and-rag": ("AI, RAG, voice & ML", [(T, 4, "T"), (T, 6, "T"), (G, 3, "G")]),
    "05-tools-and-mcp": ("Tools, MCP & force-multipliers", [(T, 5, "T"), (T, 11, "T"), (G, 4, "G")]),
}
RUN = {T: "Run 1 · toolkit standards (2026-09-21)", G: "Run 2 · GitHub repos (2026-09-22)"}

# repo-table category -> folder
REPO_DEST = {
    "02-frontend": ["🎨 Frontend UI"],
    "03-backend": ["⚙️ Backend & infra", "Mock data & testing"],
    "04-ai-and-rag": ["🤖 Data & ML", "Browser automation & scraping"],
    "05-tools-and-mcp": ["MCP servers & registries", "AI coding agents", "Claude Code skills & plugins", "Internal tools & self-host"],
    "01-hackathon-playbook": ["Public APIs & data directories", "Diagrams, slides & demo recording", "Hackathon-specific", "Mega lists"],
}


def read(p):
    with open(os.path.join(ROOT, p), encoding="utf-8") as fh:
        return fh.read()


def section(text, n):
    m = re.search(rf"^## {n}\. .*?$(.*?)(?=^## |\Z)", text, re.S | re.M)
    head = re.search(rf"^## {n}\. (.*?)$", text, re.M).group(1)
    return head, m.group(1).strip().rstrip("-").strip()


def appendix(text):
    rows = {}
    for line in text.split("## Source appendix", 1)[1].splitlines():
        m = re.match(r"\| \[(\d+)\] \|(.*)$", line)
        if m:
            rows[int(m.group(1))] = m.group(2)
    return rows


def cites(body):
    out = set()
    for a, b in re.findall(r"\[(\d+)(?:[–-](\d+))?\]", body):
        out.update(range(int(a), int(b or a) + 1))
    return sorted(out)


def write(path, content):
    full = os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as fh:
        fh.write(content)


def evidence():
    reports = {p: read(p) for p in (T, G)}
    for folder, (title, parts) in EVIDENCE.items():
        out = [f"# 🔬 Evidence: {title}\n", "<!-- markdownlint-disable MD013 MD052 -->\n",
               "> What the docs in this folder rest on, extracted from the cited research runs. "
               "Citation labels: **T** = run 1 (toolkit), **G** = run 2 (GitHub repos). "
               "Regenerated by `_research/distribute.py`, so edit the source reports rather than this file.\n"]
        src_rows, seen = [], set()
        for rep, n, pre in parts:
            head, body = section(reports[rep], n)
            app = appendix(reports[rep])
            used = cites(body)
            body = re.sub(r"\[(\d+)\]", lambda m: f"[{pre}{m.group(1)}]", body)
            rel = os.path.relpath(os.path.join(ROOT, rep), os.path.join(ROOT, folder, "docs")).replace(os.sep, "/")
            out += [f"## {RUN[rep]}: {head}\n", f"Full report: [`{os.path.basename(os.path.dirname(rep))}/research.md`]({rel})\n", body, ""]
            for i in used:
                if i in app and (pre, i) not in seen:
                    seen.add((pre, i))
                    src_rows.append(f"| [{pre}{i}] |{app[i]}")
        out += ["## Sources\n", "| # | Supports | Publisher | Pub date | Accessed | Confidence |", "| --- | --- | --- | --- | --- | --- |"]
        out += src_rows
        write(f"{folder}/docs/evidence.md", "\n".join(out) + "\n")
        print("wrote", f"{folder}/docs/evidence.md", len(src_rows), "sources")


def repos():
    text = read(TABLES)
    blocks = re.split(r"(?=^## |^### )", text, flags=re.M)
    cur_sec, grouped = None, {k: [] for k in REPO_DEST}
    for b in blocks:
        if b.startswith("## "):
            cur_sec = b.splitlines()[0][3:].strip()
            continue
        if not b.startswith("### "):
            continue
        cat = b.splitlines()[0][4:].strip()
        for folder, keys in REPO_DEST.items():
            if cat in keys or cur_sec in keys:
                grouped[folder].append(b.strip())
                break
    for folder, items in grouped.items():
        n = sum(1 for it in items for line in it.splitlines() if line.startswith("| ["))
        out = [f"# ⭐ Repos for this folder ({n})\n", "<!-- markdownlint-disable MD013 -->\n",
               "> High-star, actively maintained repos relevant to this folder, with stars, last push, license and archive status from the GitHub API (2026-09-22). "
               "`[F#]` notes refer to \"What changed in 2025–26\" in [`06-repo-catalog`](../../06-repo-catalog/README.md), which also has the default kit and the **avoid** list. "
               "Cost: repos are open source (🆓) unless the use column says otherwise; hosted services may need an account (🆓*). "
               "Regenerated by `_research/distribute.py`.\n"]
        out += [re.sub(r"^### ", "## ", i) + "\n" for i in items]
        write(f"{folder}/docs/repos.md", "\n".join(out))
        print("wrote", f"{folder}/docs/repos.md", n, "repos")


if __name__ == "__main__":
    evidence()
    repos()
