"""Build VERIFICATION.md: every claim in the guide flagged SNIPPET-ONLY, UNVERIFIED,
CONFLICT or RE-CHECK, grouped by page, as a checklist for someone with open web access.

Usage (from the repo root):
    python tools/list_unverified.py           # rewrite VERIFICATION.md
    python tools/list_unverified.py --check   # exit 1 if VERIFICATION.md is out of date

To clear an item: check the claim at its primary source, then edit the page
(replace the label with the source link, or correct the claim) and re-run this script.
"""
import os
import re
import sys

OUT = "VERIFICATION.md"
FLAG = re.compile(r"SNIPPET-ONLY|UNVERIFIED|CONFLICT|RE-CHECK|\(re-check\)", re.I)
SKIP_DIRS = {".git", "_research", ".github", "tools"}
SKIP_FILES = {OUT, "ROADMAP.md", "CONTRIBUTING.md", "THIRD_PARTY_NOTICES.md"}


def clean(line):
    line = re.sub(r"\]\([^)]*\)", "]", line)          # drop link targets
    line = re.sub(r"[*`>|]", " ", line)
    line = re.sub(r"\s+", " ", line).strip(" -")
    return line[:220] + ("…" if len(line) > 220 else "")


def is_legend(line):
    # label definitions ("SNIPPET-ONLY means ...") are not claims
    return bool(re.search(r"(SNIPPET-ONLY|UNVERIFIED|RE-CHECK)\*{0,2}\s+(means|marks)", line))


items = {}
for root, dirs, files in os.walk("."):
    dirs[:] = sorted(d for d in dirs if d not in SKIP_DIRS)
    for f in sorted(files):
        if not f.endswith(".md") or f in SKIP_FILES:
            continue
        p = os.path.join(root, f)[2:]
        inside_code = False
        for n, line in enumerate(open(p, encoding="utf-8"), 1):
            if line.lstrip().startswith("```"):
                inside_code = not inside_code
            if inside_code or not FLAG.search(line) or is_legend(line):
                continue
            items.setdefault(p, []).append((n, clean(line)))

total = sum(len(v) for v in items.values())
out = ["# Verification checklist", "", "<!-- markdownlint-disable MD013 -->", "",
       f"> Generated by `python tools/list_unverified.py`. **{total} flagged lines** across {len(items)} pages "
       "(labels SNIPPET-ONLY, UNVERIFIED, CONFLICT, RE-CHECK). Most come from research runs where the sandbox blocked primary sites. "
       "Work through a page, fix or source each claim, then re-run the script. Do not edit this file by hand.", ""]
for p in sorted(items, key=lambda k: (-len(items[k]), k)):
    out.append(f"## [`{p}`]({p}) ({len(items[p])})")
    out.append("")
    out += [f"- [ ] L{n}: {t}" for n, t in items[p]]
    out.append("")
text = "\n".join(out).rstrip() + "\n"

if "--check" in sys.argv:
    current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
    if current != text:
        print(f"{OUT} is out of date: run python tools/list_unverified.py")
        sys.exit(1)
    print(f"{OUT} up to date ({total} items)")
else:
    open(OUT, "w", encoding="utf-8").write(text)
    print(f"wrote {OUT}: {total} items across {len(items)} pages")
